### ISSUE TITLE
learn the CGtrader API and download all of or a subset of the free models

### ISSUE THREAD

**Issue by yamins81** [neuroailab/stansim#3]

**Comment by yamins81** [comment]
See https://github.com/neuroailab/stansim/blob/master/crawlers/cgtrader/cgtrader.py as a way to get started.

**Comment by hblasins** [comment]
We got an update from CGTrader on the API.

Sorry for misleading instructions on first time. It seems that we no longer include “download_url” into /v1/items/:id responses. However you can construct it manually. I prepared ruby snippet, it shows how to download each file for given model. I tested with the same credentials Dalia sent you weeks ago - it works.

```
class ApiClient
  def initialize
  end

  def connection
    @connection ||= begin
      client = OAuth2::Client.new(API_APP_ID, API_APP_SECRET, site: API_ENDPOINT) do |stack|
        stack.request :multipart
        stack.request :url_encoded
        stack.adapter Faraday.default_adapter
      end

      client.password.get_token(USER_NAME, USER_PASSWORD)
    end
  end

  def get_model(model_id)
    JSON.parse(connection.get("/v1/models/#{model_id}").body)
  end

  def get_model_file(model_id, file_id, destination)
    # Construct file_access_url manually
    file_access_url = "#{API_ENDPOINT}/v1/models/#{model_id}/files/#{file_id}"

    File.open(destination, 'wb') do |file|
      file_content = RestClient.get(file_access_url, params: { access_token: connection.token })
      file.write(file_content)
    end
  end
end

api_client = ApiClient.new

model_id = 77169
model = api_client.get_model(model_id)

model['files'].each do |file|
  puts "Download: #{file['name']}"
  api_client.get_model_file(model_id, file['id'], "#{TMP}/#{file['name']}")
end
```

**Comment by yamins81** [comment]
It would be great to get this translated into python (along the lines of the other python snippet that I committed.)

**Comment by hblasins** [comment]
I've already pushed a few commits. We now have python code to download all the model files, given a model ID. In theory one could try all the numbers from 0 to infinity to see which models are free, but perhaps there is a smarter way to do this, and to save some model categories along the way as well.

**Comment by yamins81** [comment]
I assume there's some way to fetch price with the API?  If not obvious maybe ask the CGTrader people?

**Comment by hblasins** [comment]
Yes there is, I think I’m displaying the price of the object in one of the functions.


Wiadomość napisana przez Dan Yamins <notifications@github.com<mailto:notifications@github.com>> w dniu 21.12.2016, o godz. 18:18:


I assume there's some way to fetch price with the API? If not obvious maybe ask the CGTrader people?

**Comment by ZilvinasKucinskas** [comment]
Hey, CGTrader API was updated today to enable possibility to search by category or subcategory (using `category_id` query parameter), please check [`GET /v1/models` endpoint](https://api.cgtrader.com/docs/_v1_models_get_69871741936180.html). Full documentation of API endpoints available [here](https://api.cgtrader.com/docs/index.html).

Also there is possibility to filter by the price - that way you can obtain the exact price of the model or search free models. Cheers and have a great day!

**Comment by hblasins** [comment]
Excellent!
I've played with the updated API and started to download the models.

**Comment by hblasins** [comment]
Done

**Comment by player360-kali** [comment]
Hello everybody!
https://www.cgtrader.com/3d-models/exterior/landmark/la-casa-de-papel-final-cut

I want to download the 3D model but I haven't money :)

Who can get the 3D model. @hblasins I think you made a tool for get 3D models. Can you get for me?
